### ISSUE TITLE
'PR can be merged' message are not sent

### ISSUE THREAD

**Issue by roman-kozachenko** [aensidhe/merge-queue-bot#6]
I wanted to add my PR to merge queue.
In private chat, i sent message /add <Link to PR> to merge queue bot. 
Before i did that, merge queue were empty.
I expected that merge bot sent me a message that i'm on the top of queue and can merge my PR, but it didn't.
/queue command sent to private didn't have an affect (possible is it ok).
/queue on common chat shows me, that I first in merge queue.

**Comment by aensidhe** [comment]
Protected branches API is still in preview. Will not support it until it released. https://developer.github.com/changes/2016-06-27-protected-branches-api-update/
